[package]
name = "rust-app"
version = "0.1.0"
authors = ["SachinMaharana <sachin.nicky@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "1.0.0-alpha.4"
env_logger = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
hostname = "0.1.5"